spring:
  main:
    web-environment: true
    show-banner: false
  datasource:
    url: "jdbc:mysql://database:3306/aa_model_service?autoReconnect=true"
    username: ${USERNAME:root}
    password: ${PASSWORD:""}
    maximum-pool-size: 8
    minimum-idle: 0
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    openInView: true
    database: "MYSQL"
    show-sql: false
    generate-ddl: false
    hibernate:
      naming_strategy: "org.hibernate.cfg.ImprovedNamingStrategy"
  data:
    rest:
      base-path: "/api"
endpoints:
  health:
    sensitive: false

# Swagger Documentation
swagger:
  service:
    version: "1.0.0"
    title: "Model service detector mapper"
    description: "A service that provides APIs for model-service-detector-mapper"
    termsPath: ""
    contact:
      name: "EWE Platform"
      email: "EWE Platform@expedia.com"
    licencePath: "#"
    licenceType: ""

# Additional Config
test:
  helloMsg: "Hello there"

vault:
  host: ${spring.cloud.vault.uri}

es:
  enabled: true
  index.name: detector_mappings
  doctype: details
  urls: localhost:9001
  connection.timeout: 40000
  max.connection.idletime: 1000
  max.total.connection: 2000
  read.timeout: 1000

model-service:
  find-latest-changes-url: http://localhost:8008/detector-mapping/last-updated?timeInSecs=65

management:
  context-path: "/admin"
  metrics:
    export:
      jmx:
        domain: spring
    enable:
      jvm: false
      tomcat: false
      system: false
      process: false
security:
  clientId: "id"
  secret: "secret"
  signingKey: "1234"
server:
  port: 8008
